services:
  server:
    image: 264642482083.dkr.ecr.us-east-1.amazonaws.com/bia:$TAG
    container_name: bia
    ports:
      - 80:8080
    environment:
      DB_USER: postgres
      DB_PWD: 
      DB_PORT: 5432
      DB_HOST:  